import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';

import { AppContextProvider } from '@/contexts/app';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-josefin-sans',
  fallback: ['sans-serif']
});

import './globals.css';
import ToastList from '@/app/components/ToastList';

export const metadata: Metadata = {
  title: {
    template: 'Todo | %s',
    default: 'Todo'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  /* supressHydrationWarning prop is necessary for next-themes library to work properly

    Source: https://github.com/pacocoursey/next-themes#with-app
  */

  return (
    <html lang='en' className={`${josefinSans.variable}`} suppressHydrationWarning>
      <body className='font-primary text-lg bg-very-light-grayish-blue dark:bg-very-dark-blue'>
        <AppContextProvider>
          {children}

          <ToastList />
        </AppContextProvider>

      </body>
    </html>
  )
}
